#!/bin/bash
# Script para ver la estructura del proyecto de forma visual

echo "📦 ESTRUCTURA DEL PROYECTO WIZZPRO"
echo "=================================="
echo ""

echo "📂 Raíz del proyecto:"
echo "  ├── package.json"
echo "  ├── tsconfig.json"
echo "  ├── next.config.ts"
echo "  ├── tailwind.config.ts"
echo "  ├── postcss.config.mjs"
echo "  └── eslint.config.mjs"
echo ""

echo "📂 app/ (Aplicación Next.js)"
echo "  ├── 📄 layout.tsx (Estructura HTML)"
echo "  ├── 📄 page.tsx (Página principal - LIMPIA)"
echo "  ├── 📄 globals.css"
echo "  ├── 🎨 favicon.ico"
echo "  │"
echo "  ├── 📂 components/ (7 componentes)"
echo "  │   ├── Navbar.tsx ✨"
echo "  │   ├── HeroSection.tsx ✨"
echo "  │   ├── AwardsSection.tsx ✨"
echo "  │   ├── AwardCard.tsx ✨"
echo "  │   ├── SocialLinks.tsx ✨"
echo "  │   ├── SocialIcons.tsx ✨"
echo "  │   └── index.ts (Exporta todos)"
echo "  │"
echo "  ├── 📂 constants/ (Datos)"
echo "  │   └── raffleData.ts (Datos de la rifa)"
echo "  │"
echo "  ├── 📂 types/ (TypeScript)"
echo "  │   └── index.ts (Interfaces)"
echo "  │"
echo "  ├── 📂 config/ (Configuración)"
echo "  │   └── index.ts (Variables globales)"
echo "  │"
echo "  ├── 📂 hooks/ (Custom Hooks)"
echo "  │   └── index.ts (useNavigation, useAwardActions)"
echo "  │"
echo "  └── 📂 utils/ (Funciones auxiliares)"
echo "      └── index.ts (formatCurrency, buildWhatsAppUrl, etc)"
echo ""

echo "📚 Documentación:"
echo "  ├── README.md (Este archivo)"
echo "  ├── ESTRUCTURA.md (Explicación detallada)"
echo "  ├── GUIA_DESARROLLO.md (Cómo trabajar)"
echo "  ├── ARQUITECTURA.md (Diagramas)"
echo "  ├── EJEMPLO_COMPONENTE.tsx (Patrón)"
echo "  └── README_REFACTORING.md (Resumen)"
echo ""

echo "🎯 ESTADÍSTICAS"
echo "==============="
echo "  • Componentes: 7 ✨"
echo "  • Archivos de configuración: 3 ⚙️"
echo "  • Tipos TypeScript: 2 📝"
echo "  • Custom Hooks: 2 🪝"
echo "  • Funciones utilitarias: 4 🛠️"
echo "  • Documentación: 5 archivos 📚"
echo ""

echo "✅ BENEFICIOS"
echo "============="
echo "  ✓ Modular - Componentes independientes"
echo "  ✓ Escalable - Fácil agregar nuevos componentes"
echo "  ✓ Mantenible - Código organizado"
echo "  ✓ Tipado - TypeScript para seguridad"
echo "  ✓ Profesional - Sigue best practices"
echo "  ✓ Documentado - Documentación completa"
echo ""

echo "🚀 COMANDOS ÚTILES"
echo "=================="
echo "  npm run dev          - Iniciar desarrollo"
echo "  npm run build        - Compilar para producción"
echo "  npm run start        - Iniciar en producción"
echo "  npm run lint         - Verificar código"
echo ""

echo "📖 PARA EMPEZAR"
echo "==============="
echo "  1. Lee GUIA_DESARROLLO.md"
echo "  2. Ve ARQUITECTURA.md para entender el flujo"
echo "  3. Usa EJEMPLO_COMPONENTE.tsx como referencia"
echo "  4. ¡Comienza a desarrollar! 🎉"
echo ""
